controller_list:
  - name: fake_manipulator_controller
    type: $(arg fake_execution_type)
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
  - name: fake_end_controller
    type: $(arg fake_execution_type)
    joints:
      - joint4
      - gripper
initial:  # Define initial robot poses per group
  - group: manipulator
    pose: home